### ISSUE TITLE
potodo fails on divide by 0

### ISSUE THREAD

**Issue by Seluj78** [AFPy/Potodo#101]
If you run potodo in the potodo folder, you get a divide by 0 error

**Comment by Seluj78** [comment]
hmm cannot reproduce now

**Comment by vpoulailleau** [comment]
Well this fails:

```sh
python3 -m potodo -p /home/vincent/Documents/programmation/name-photos-by-date/
```

To make it fail, you have to execute potodo in a git-versioned folder without any po files…

For a non git-versioned folder, you get:

```
Traceback (most recent call last):
  File "/home/vincent/Documents/programmation/Potodo/potodo/github.py", line 17, in get_repo_url
    url = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', '--all', 'upstream']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vincent/Documents/programmation/Potodo/potodo/github.py", line 25, in get_repo_url
    url = subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'remote', 'get-url', '--all', 'origin']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vincent/Documents/programmation/Potodo/potodo/__main__.py", line 3, in <module>
    __import__("potodo.potodo").potodo.main()
  File "/home/vincent/Documents/programmation/Potodo/potodo/potodo.py", line 492, in main
    exec_potodo(**args)
  File "/home/vincent/Documents/programmation/Potodo/potodo/potodo.py", line 130, in exec_potodo
    issue_reservations = get_issue_reservations(offline, hide_reserved, path)
  File "/home/vincent/Documents/programmation/Potodo/potodo/github.py", line 98, in get_issue_reservations
    issue_reservations = _get_reservation_list(repo_path)
  File "/home/vincent/Documents/programmation/Potodo/potodo/github.py", line 61, in _get_reservation_list
    + get_repo_name(repo_path)
  File "/home/vincent/Documents/programmation/Potodo/potodo/github.py", line 43, in get_repo_name
    repo_url = get_repo_url(repo_path)
  File "/home/vincent/Documents/programmation/Potodo/potodo/github.py", line 32, in get_repo_url
    raise RuntimeError(
RuntimeError: Unknown error. `git remote get-url --all origin` returned "fatal: ni ceci ni aucun de ses répertoires parents n'est un dépôt git : .git".
```

Should the division be fixed (happens only without any po file!), this is a division by the number of entries to translated, including translated ones?

**Comment by Seluj78** [comment]
Well on `0.19.1` the ousite of git is fixed

```
(venv) ➜  python-docs-fr git:(3.9) potodo -p ~/
potodo needs to be ran in a git repository, or use the `-p` `--path` argument.
```

Now for the divide by zero, I added a condition at the end of your code (here https://github.com/AFPy/Potodo/blob/master/potodo/potodo.py#L157)

I dont understand your question tho

**Comment by vpoulailleau** [comment]
I was wondering if it was useful to correct it, but you did the job. So it's OK like this :wink:

**Comment by Seluj78** [comment]
Cool !
