### ISSUE TITLE
potodo doesn't work on windows 10

### ISSUE THREAD

**Issue by Bot57** [AFPy/Potodo#117]
Après essai d'installation de potodo pour aider sur la traduction de python, echec critique

```
λ python -m potodo
Traceback (most recent call last):
  File "D:\Programmation\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programmation\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Programmation\Traduction\potodo\io\lib\site-packages\potodo\__main__.py", line 3, in <module>
    __import__("potodo.potodo").potodo.main()
  File "D:\Programmation\Traduction\potodo\io\lib\site-packages\potodo\potodo.py", line 488, in main
    exec_potodo(**args)
  File "D:\Programmation\Traduction\potodo\io\lib\site-packages\potodo\potodo.py", line 203, in exec_potodo
    non_interactive_output(
  File "D:\Programmation\Traduction\potodo\io\lib\site-packages\potodo\potodo.py", line 84, in non_interactive_output
    issue_reservations = get_issue_reservations(offline, hide_reserved, path)
  File "D:\Programmation\Traduction\potodo\io\lib\site-packages\potodo\github.py", line 99, in get_issue_reservations
    issue_reservations = _get_reservation_list(repo_path)
  File "D:\Programmation\Traduction\potodo\io\lib\site-packages\potodo\github.py", line 80, in _get_reservation_list
    yes = re.search(r"\w*/\w*\.po", issue["title"])
TypeError: string indices must be integers
```

Bisoux

**Comment by JulienPalard** [comment]
J'ai fait une tentative de rendre cette erreur plus explicite pour la comprendre, peux-tu retester après :

    pip install git+https://github.com/JulienPalard/potodo@mdk/TypeError

et nous dire quoi ?

**Comment by deronnax** [comment]
J'ai fait la commande et j'ai plus l'erreur. Mais en reinstallant la version de PyPI, je n'ai plus l'erreur non plus. Je ne comprends pas 🤷‍♂️

**Comment by Seluj78** [comment]
On close du coup ?

**Comment by JulienPalard** [comment]
Du coup quelqu'un pourra toujours réouvrir s'il peut reproduire l'erreur.
