### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by deronnax** [AFPy/Potodo#122]
```
Traceback (most recent call last):
  File "/Users/mathieudupuy/.pyenv/versions/3.6.15/bin/potodo", line 8, in <module>
    sys.exit(main())
  File "/Users/mathieudupuy/.pyenv/versions/3.6.15/lib/python3.6/site-packages/potodo/potodo.py", line 232, in main
    args.no_reserved,
  File "/Users/mathieudupuy/.pyenv/versions/3.6.15/lib/python3.6/site-packages/potodo/potodo.py", line 78, in exec_potodo
    issue_reservations = get_gh_issue_reservation()
  File "/Users/mathieudupuy/.pyenv/versions/3.6.15/lib/python3.6/site-packages/potodo/potodo.py", line 23, in get_gh_issue_reservation
    issue["title"].split()[-1].lower(): issue["user"]["login"] for issue in issues
  File "/Users/mathieudupuy/.pyenv/versions/3.6.15/lib/python3.6/site-packages/potodo/potodo.py", line 23, in <dictcomp>
    issue["title"].split()[-1].lower(): issue["user"]["login"] for issue in issues
TypeError: string indices must be integers
``` 

looks a bit similar to #117

**Comment by JulienPalard** [comment]
Did you tried https://github.com/AFPy/Potodo/issues/117#issuecomment-806080136?
